# Generated by Django 2.2.3 on 2019-11-30 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('actor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
                ('aimed_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aimed_at', to='main_app.Character')),
                ('said_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='said_by', to='main_app.Character')),
            ],
        ),
    ]
