# Generated by Django 2.2.3 on 2019-11-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191130_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
